### ISSUE TITLE
Mine issues

### ISSUE THREAD

**Issue by Murder4Hyre** [MayhemServers/MAYHEM_A3Wasteland.Altis#1]
- Friendly Mines do not appear to friendlies on the server (usually a red triangle)
- Mine Detector does not appear to work at all
- Mines can be set at the gunstores (Kavala, Pyrgos, Abdera)

**Comment by osuapoc** [comment]
Item 3 fixed with 250a4c2654e8fdeccd386ec9758369b1690018f9
Item 2 now has an alternative 9f617e5fd24be374dd4d4a492df3cad5e00513f2

Still need to address the friendly mine markers.
