### ISSUE TITLE
Admins cannot see ATM accounts

### ISSUE THREAD

**Issue by Murder4Hyre** [MayhemServers/MAYHEM_A3Wasteland.Altis#11]
Admins cannot see bank ATM amounts in Stratis

**Comment by LouDnl** [comment]
You could change/add this. Then you will see players bank amounts in the playermanagement tool.
https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/5d8469653964fc689dd4a4870ecaacabba60f3f2

**Comment by osuapoc** [comment]
Thanks, @LouDnl .  Murder was speaking of our other server (Stratis) which has since been updated with code to display the current money (cash/bank).  The value is populated via the importvalues.sqf, around line 75.
