### ISSUE TITLE
ATM limit for supporters

### ISSUE THREAD

**Issue by Murder4Hyre** [MayhemServers/MAYHEM_A3Wasteland.Altis#16]
Currently supporters are still limited to 2 mil in their ATM accounts.  Should be 4 mil.

**Comment by osuapoc** [comment]
Should be fixed in 272e180fefd30caea2f5f5fb7e9a4b08af72cfc4.  Tested on my machine and seems to be A-OK.  Max account balance depends on donator level; level 4 is 4 mill, but 2&3 are 3mill I believe.
