### ISSUE TITLE
BIS_fnc_MP

### ISSUE THREAD

**Issue by LouDnl** [MayhemServers/MAYHEM_A3Wasteland.Altis#19]
Hey Apoc,

Your aidrop script uses BIS_fnc_MP here: https://github.com/MayhemServers/MAYHEM_A3Wasteland.Altis/blob/Development_main/addons/APOC_Airdrop_Assistance/APOC_cli_startAirdrop.sqf#L50

According to: https://community.bistudio.com/wiki/BIS_fnc_MP
We should not use it anymore?

Have you checked this?

**Comment by LouDnl** [comment]
More information here: https://community.bistudio.com/wiki/Arma_3_Remote_Execution

**Comment by osuapoc** [comment]
Yes, actually I was looking at that while I prepare an Exile version.  The only real thing to watch for is that you need to define the function being called in a white list if you've disabled remoteExec calls. Otherwise, BIS_fnc_MP is still functional and viable.

-----Original Message-----

**Comment by LouDnl** [comment]
Is there an easy fix?

**Comment by osuapoc** [comment]
Well, nothing needs changed in the airdrop, but where you set the CfgRemoteExec white list needs the APOC_srv_start... Function added with the target set to allow remote exec on the server from a client. 

I'll post a note about that on the forum when I'm free at lunch in a couple hours. 

-----Original Message-----

**Comment by osuapoc** [comment]
Explanation posted on forums:
http://forums.a3wasteland.com/index.php?topic=1450.msg13771#msg13771
Closing issue.
